### ISSUE TITLE
Requesting you pull, please: Reporobot reports "too many files" in /contributors/ but git-it verify passes

### ISSUE THREAD

**Issue by brianjsullivan** [jlord/git-it#164] opened 2015-04-16 15:48 UTC
I followed the git-it process step by step, and wound up with ALL the add-USERNAME /contributors/ files in my local add-USERNAME branch. Despite following all the steps exactly, after making a pull request to the forked repo, reporobot reports: Uh oh, I see too many files, there should be one: contributors/add-USERNAME.

When running git-it verify at this point, I pass, despite the pull request not being successful (it exists, just doesn't follow through because of this discrepancy).

So I delete the extra files locally, checkout the deleted files locally, commit to origin add-USERNAME, push to origin add-USERNAME and manually do the pull request again. Same result. It reports too many files in /contributors/ despite there only being ONE (add-USERNAME.txt) on both my local and remote branch.

**Comment by jlord** [comment] 2015-09-19 05:00
This is a dupe of #156. Consolidating :+1:

**Closed by jlord** 2015-09-19 05:00 UTC
